on:
  workflow_run:
    workflows: ["Main Taski workflow"]
    types:
      - completed

jobs:
  trig_selfhosted:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted]
    steps:
      - name: Do stuff on self-hosted runner
        run: echo "External job started!"
